modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="fresh_arms_and_armor"
version="0.1.0"
displayName="Fresh Arms & Armor"
authors="fresh_squilliam"
description='''
Adds class-based weapons and armor with distinct playstyles.
'''

[[dependencies.fresh_arms_and_armor]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.fresh_arms_and_armor]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,)"
ordering="NONE"
side="BOTH"
