modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="fresharmsandarmor"
version="0.2.2"
displayName="Fresh Arms and Armor"
authors="fresh_squilliam"
description='''
Adds Fantasy RPG martial classes to Minecraft
'''

[[dependencies.fresharmsandarmor]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.fresharmsandarmor]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,)"
ordering="NONE"
side="BOTH"
