
[barbarian]
	#Damage bonus per IRON Barbarian armor piece (e.g. 0.05 = +5%)
	#Range: 0.0 ~ 10.0
	iron_bonus = 0.05
	#Damage bonus per DIAMOND Barbarian armor piece
	#Range: 0.0 ~ 10.0
	diamond_bonus = 0.075
	#Damage bonus per NETHERITE Barbarian armor piece
	#Range: 0.0 ~ 10.0
	netherite_bonus = 0.1

