
["Barbarian Armor"]
	#Damage bonus per piece of Iron Barbarian armor (0.05 = 5%)
	#Range: 0.0 ~ 5.0
	ironBonus = 0.05
	#Damage bonus per piece of Diamond Barbarian armor (0.075 = 7.5%)
	#Range: 0.0 ~ 5.0
	diamondBonus = 0.075
	#Damage bonus per piece of Netherite Barbarian armor (0.10 = 10%)
	#Range: 0.0 ~ 5.0
	netheriteBonus = 0.1

["Knight Armor"]
	#Damage bonus per piece of Iron Knight armor (0.04 = 4%)
	#Range: 0.0 ~ 5.0
	ironBonus = 0.04
	#Damage bonus per piece of Diamond Knight armor (0.06 = 6%)
	#Range: 0.0 ~ 5.0
	diamondBonus = 0.06
	#Damage bonus per piece of Netherite Knight armor (0.08 = 8%)
	#Range: 0.0 ~ 5.0
	netheriteBonus = 0.08

